"""master fund and contracts

Revision ID: 33f4a5e6663b
Revises: 6700f1d06c70
Create Date: 2026-09-04 13:04:31.104816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33f4a5e6663b'
down_revision: Union[str, Sequence[str], None] = '6700f1d06c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_clauses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('contract_type', sa.String(), nullable=False),
    sa.Column('madhhab', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('certification_ref', sa.String(), nullable=True),
    sa.Column('scholar', sa.String(), nullable=True),
    sa.Column('certified_on', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_clauses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_clauses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_clauses_key'), ['key'], unique=True)

    op.create_table('contract_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('contract_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('clause_order', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_templates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_templates_name'), ['name'], unique=True)

    op.create_table('master_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('master_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_entities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_entities_name'), ['name'], unique=True)

    op.create_table('capital_pools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_entity_id', sa.Integer(), nullable=False),
    sa.Column('total_capital', sa.Float(), nullable=True),
    sa.Column('unallocated_capital', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['master_entity_id'], ['master_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_entity_id')
    )
    with op.batch_alter_table('capital_pools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capital_pools_id'), ['id'], unique=False)

    op.create_table('allocation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_entity_id', sa.Integer(), nullable=False),
    sa.Column('target_company_id', sa.Integer(), nullable=False),
    sa.Column('basis', sa.Enum('FIXED_AMOUNT', 'PERCENTAGE_OF_POOL', 'CAPITAL_RATIO', 'PERFORMANCE', 'NEEDS_BASED', 'MANUAL', name='allocationbasisenum'), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('max_cap', sa.Float(), nullable=True),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['master_entity_id'], ['master_entities.id'], ),
    sa.ForeignKeyConstraint(['target_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allocation_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allocation_rules_id'), ['id'], unique=False)

    op.create_table('allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_entity_id', sa.Integer(), nullable=False),
    sa.Column('target_company_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['master_entity_id'], ['master_entities.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['allocation_rules.id'], ),
    sa.ForeignKeyConstraint(['target_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allocations_id'), ['id'], unique=False)

    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.alter_column('agreement_type',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('PARAMETER_CHANGE', 'PERIOD_CLOSE', 'MASTER_ALLOCATION', name='agreementtype'),
               existing_nullable=True)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('master_entity_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_companies_master_entity_id', 'master_entities', ['master_entity_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_companies_master_entity_id', type_='foreignkey')
        batch_op.drop_column('master_entity_id')

    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.alter_column('agreement_type',
               existing_type=sa.Enum('PARAMETER_CHANGE', 'PERIOD_CLOSE', 'MASTER_ALLOCATION', name='agreementtype'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allocations_id'))

    op.drop_table('allocations')
    with op.batch_alter_table('allocation_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allocation_rules_id'))

    op.drop_table('allocation_rules')
    with op.batch_alter_table('capital_pools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capital_pools_id'))

    op.drop_table('capital_pools')
    with op.batch_alter_table('master_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_entities_name'))
        batch_op.drop_index(batch_op.f('ix_master_entities_id'))

    op.drop_table('master_entities')
    with op.batch_alter_table('contract_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_templates_name'))
        batch_op.drop_index(batch_op.f('ix_contract_templates_id'))

    op.drop_table('contract_templates')
    with op.batch_alter_table('contract_clauses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_clauses_key'))
        batch_op.drop_index(batch_op.f('ix_contract_clauses_id'))

    op.drop_table('contract_clauses')
    # ### end Alembic commands ###
