"""Add AuditLog, UserCompanyLink, and Master models

Revision ID: 5eef48576b6e
Revises: bf76a45cf4ba
Create Date: 2026-09-06 17:53:59.959341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eef48576b6e'
down_revision: Union[str, Sequence[str], None] = 'bf76a45cf4ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
