"""hanafi fix drop labour share mode

Revision ID: 6700f1d06c70
Revises: 88d2cc2fff38
Create Date: 2026-09-04 13:00:20.420738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6700f1d06c70'
down_revision: Union[str, Sequence[str], None] = '88d2cc2fff38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('labour_share_mode')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('labour_share_mode', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
