"""Add pluggable signing models

Revision ID: 6e9d55a8b20e
Revises: ed25c6be6cac
Create Date: 2026-09-07 11:03:27.018235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e9d55a8b20e'
down_revision: Union[str, Sequence[str], None] = 'ed25c6be6cac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
