"""Add Master Fund Layer

Revision ID: b2c0b9ac31cc
Revises: 17949c86d4a1
Create Date: 2026-09-05 15:06:40.179355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'b2c0b9ac31cc'
down_revision: Union[str, Sequence[str], None] = '17949c86d4a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_agreements')
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.alter_column('agreement_type',
               existing_type=sa.VARCHAR(length=17),
               type_=sa.Enum('PARAMETER_CHANGE', 'PERIOD_CLOSE', name='agreementtype'),
               existing_nullable=True)

    with op.batch_alter_table('allocation_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pool_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('schedule_cron', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cap_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('basis',
               existing_type=sa.VARCHAR(length=18),
               nullable=False)
        batch_op.create_foreign_key('fk_allocation_rules_companies', 'companies', ['company_id'], ['id'])
        batch_op.create_foreign_key('fk_allocation_rules_pools', 'capital_pools', ['pool_id'], ['id'])
        batch_op.drop_column('max_cap')
        batch_op.drop_column('target_company_id')
        batch_op.drop_column('master_entity_id')
        batch_op.drop_column('schedule')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('allocations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pool_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('allocated_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_allocations_pools', 'capital_pools', ['pool_id'], ['id'])
        batch_op.create_foreign_key('fk_allocations_companies', 'companies', ['company_id'], ['id'])
        batch_op.drop_column('date')
        batch_op.drop_column('master_entity_id')
        batch_op.drop_column('target_company_id')

    with op.batch_alter_table('capital_pools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('total_balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('total_capital')
        batch_op.drop_column('unallocated_capital')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capital_pools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unallocated_capital', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('total_capital', sa.FLOAT(), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('total_balance')
        batch_op.drop_column('name')

    with op.batch_alter_table('allocations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_company_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('master_entity_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))
        batch_op.create_foreign_key(None, 'companies', ['target_company_id'], ['id'])
        batch_op.create_foreign_key(None, 'master_entities', ['master_entity_id'], ['id'])
        batch_op.drop_column('allocated_at')
        batch_op.drop_column('company_id')
        batch_op.drop_column('pool_id')

    with op.batch_alter_table('allocation_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('schedule', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('master_entity_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('target_company_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('max_cap', sa.FLOAT(), nullable=True))
        batch_op.create_foreign_key(None, 'companies', ['target_company_id'], ['id'])
        batch_op.create_foreign_key(None, 'master_entities', ['master_entity_id'], ['id'])
        batch_op.alter_column('basis',
               existing_type=sa.VARCHAR(length=18),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('cap_amount')
        batch_op.drop_column('schedule_cron')
        batch_op.drop_column('company_id')
        batch_op.drop_column('pool_id')

    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.alter_column('agreement_type',
               existing_type=sa.Enum('PARAMETER_CHANGE', 'PERIOD_CLOSE', name='agreementtype'),
               type_=sa.VARCHAR(length=17),
               existing_nullable=True)

    op.create_table('_alembic_tmp_agreements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company_id', sa.INTEGER(), nullable=False),
    sa.Column('proposed_by_id', sa.INTEGER(), nullable=False),
    sa.Column('proposed_settings', sqlite.JSON(), nullable=True),
    sa.Column('proposed_shares', sqlite.JSON(), nullable=True),
    sa.Column('negligent_user_id', sa.INTEGER(), nullable=True),
    sa.Column('period_name', sa.VARCHAR(), nullable=True),
    sa.Column('agreement_type', sa.VARCHAR(length=16), nullable=True),
    sa.Column('change_summary', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=10), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('effective_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['negligent_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['proposed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_company_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_company_links_id'))

    op.drop_table('user_company_links')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
