"""Initial

Revision ID: bf76a45cf4ba
Revises: 
Create Date: 2026-09-06 03:06:25.921018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf76a45cf4ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_name'), ['name'], unique=True)

    op.create_table('contract_clauses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('contract_type', sa.String(), nullable=False),
    sa.Column('madhhab', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('certification_ref', sa.String(), nullable=True),
    sa.Column('scholar', sa.String(), nullable=True),
    sa.Column('certified_on', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_clauses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_clauses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_clauses_key'), ['key'], unique=True)

    op.create_table('contract_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('contract_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('clause_order', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_templates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_templates_name'), ['name'], unique=True)

    op.create_table('document_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_sections_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'COMPANY_ADMIN', 'PARTNER', name='roleenum'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('mfa_secret', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE', name='accounttypeenum'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_name'), ['name'], unique=False)

    op.create_table('agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('proposed_by_id', sa.Integer(), nullable=False),
    sa.Column('proposed_settings', sa.JSON(), nullable=True),
    sa.Column('proposed_shares', sa.JSON(), nullable=True),
    sa.Column('negligent_user_id', sa.Integer(), nullable=True),
    sa.Column('period_name', sa.String(), nullable=True),
    sa.Column('agreement_type', sa.Enum('PARAMETER_CHANGE', 'PERIOD_CLOSE', name='agreementtype'), nullable=True),
    sa.Column('change_summary', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'EXECUTED', 'REJECTED', 'SUPERSEDED', name='agreementstatus'), nullable=True),
    sa.Column('effective_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['negligent_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['proposed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agreements_id'), ['id'], unique=False)

    op.create_table('company_document_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_document_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_document_sections_id'), ['id'], unique=False)

    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('charity_percentage', sa.Float(), nullable=True),
    sa.Column('partnership_mode', sa.String(), nullable=True),
    sa.Column('labour_share_mode', sa.String(), nullable=True),
    sa.Column('currency_symbol', sa.String(), nullable=True),
    sa.Column('is_setup_complete', sa.Boolean(), nullable=True),
    sa.Column('capital_pool_percentage', sa.Float(), nullable=True),
    sa.Column('labour_pool_percentage', sa.Float(), nullable=True),
    sa.Column('contingency_pot_minimum', sa.Float(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('favicon_url', sa.String(), nullable=True),
    sa.Column('primary_color', sa.String(), nullable=True),
    sa.Column('secondary_color', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_global_settings_id'), ['id'], unique=False)

    op.create_table('monthly_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('period_name', sa.String(), nullable=False),
    sa.Column('net_profit', sa.Float(), nullable=False),
    sa.Column('global_charity', sa.Float(), nullable=False),
    sa.Column('voluntary_charity', sa.Float(), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monthly_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_reports_id'), ['id'], unique=False)

    op.create_table('partner_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('capital_share_fixed', sa.Float(), nullable=True),
    sa.Column('labor_share_variable', sa.Float(), nullable=True),
    sa.Column('voluntary_charity_percentage', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partner_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_shares_id'), ['id'], unique=False)

    op.create_table('signing_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('MANUAL', 'DOCUMENSO', 'DOCUSIGN', name='providertype'), nullable=True),
    sa.Column('encrypted_credentials', sa.LargeBinary(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    with op.batch_alter_table('signing_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signing_configs_id'), ['id'], unique=False)

    op.create_table('time_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_entries_id'), ['id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('is_reversing', sa.Boolean(), nullable=True),
    sa.Column('original_transaction_id', sa.Integer(), nullable=True),
    sa.Column('is_pending', sa.Boolean(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['original_transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_id'), ['id'], unique=False)

    op.create_table('agreement_signoffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'EXECUTED', 'REJECTED', 'SUPERSEDED', name='agreementstatus'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agreement_signoffs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agreement_signoffs_id'), ['id'], unique=False)

    op.create_table('company_section_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('global_section_id', sa.Integer(), nullable=True),
    sa.Column('company_section_id', sa.Integer(), nullable=True),
    sa.Column('is_included', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_section_id'], ['company_document_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['global_section_id'], ['document_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_section_selections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_section_selections_id'), ['id'], unique=False)

    op.create_table('expense_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('receipt_url', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    with op.batch_alter_table('expense_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_receipts_id'), ['id'], unique=False)

    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('type', sa.Enum('DEBIT', 'CREDIT', name='entrytypeenum'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_id'), ['id'], unique=False)

    op.create_table('signing_envelopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('MANUAL', 'DOCUMENSO', 'DOCUSIGN', name='providertype'), nullable=False),
    sa.Column('provider_ref', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'PARTIALLY_SIGNED', 'COMPLETED', 'DECLINED', 'VOIDED', name='envelopestatus'), nullable=True),
    sa.Column('signed_document_ref', sa.String(), nullable=True),
    sa.Column('audit_log', sa.JSON(), nullable=True),
    sa.Column('template_version', sa.String(), nullable=True),
    sa.Column('shariah_certification_ref', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agreement_id')
    )
    with op.batch_alter_table('signing_envelopes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signing_envelopes_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signing_envelopes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signing_envelopes_id'))

    op.drop_table('signing_envelopes')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_id'))

    op.drop_table('journal_entries')
    with op.batch_alter_table('expense_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_receipts_id'))

    op.drop_table('expense_receipts')
    with op.batch_alter_table('company_section_selections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_section_selections_id'))

    op.drop_table('company_section_selections')
    with op.batch_alter_table('agreement_signoffs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agreement_signoffs_id'))

    op.drop_table('agreement_signoffs')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_entries_id'))

    op.drop_table('time_entries')
    with op.batch_alter_table('signing_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signing_configs_id'))

    op.drop_table('signing_configs')
    with op.batch_alter_table('partner_shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_shares_id'))

    op.drop_table('partner_shares')
    with op.batch_alter_table('monthly_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_reports_id'))

    op.drop_table('monthly_reports')
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_settings_id'))

    op.drop_table('global_settings')
    with op.batch_alter_table('company_document_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_document_sections_id'))

    op.drop_table('company_document_sections')
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agreements_id'))

    op.drop_table('agreements')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_name'))
        batch_op.drop_index(batch_op.f('ix_accounts_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('document_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_sections_id'))

    op.drop_table('document_sections')
    with op.batch_alter_table('contract_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_templates_name'))
        batch_op.drop_index(batch_op.f('ix_contract_templates_id'))

    op.drop_table('contract_templates')
    with op.batch_alter_table('contract_clauses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_clauses_key'))
        batch_op.drop_index(batch_op.f('ix_contract_clauses_id'))

    op.drop_table('contract_clauses')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_name'))
        batch_op.drop_index(batch_op.f('ix_companies_id'))

    op.drop_table('companies')
    # ### end Alembic commands ###
